# Generated by Django 4.2.2 on 2023-07-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_topics_and_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
